name: "Custom Github Actions"
description: "Quick demo container action"
inputs:
  username:
    description: "Username"
    required: true
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    username: ${{ inputs.username }} 