"use strict";
exports.__esModule = true;
var core = require("@actions/core");
var github = require("@actions/github");
var payload = JSON.stringify(github.context.payload, undefined, 2);
var version = "1.0.0";
var prefix = core.getInput('prefix-tag');
var token = core.getInput('github-token');
console.log("The event payload: ".concat(payload));
core.setOutput("new-tag", version);
