name: "Custom Github Actions"
description: "Quick demo action"
inputs:
  username:
    description: "Username"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Hello ${{ inputs.username }}"
      shell: bash    