name: "Custom Github Actions"
description: "Quick demo javascript action"
inputs:
  github-token:
    description: "Token"
    required: true
  prefix-tag:
    description: "Service name as prefix for tag"
    required: true
outputs:
  new-tag:
    description: "Output from the action"
runs:
  using: "node16"
  main: "lib/index.js"
  
    