name: "Run Custom Actions"
on:
  #Manual trigger
  workflow_dispatch:
  #run changes
  push:

jobs:
  custom-actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Custom Composite Actions
        uses: ./sh
        with:
          username: "John Doe"
      - name: Custom Javascript Actions
        uses: ./javascript
        with:
          prefix-tag: "customer"
          github-token: ${{ secrets.GITHUB_TOKEN }}    
      - name: Print value
        run: echo "The value is ${{ steps.custom-actions-job.outputs.myOutput }}"